Enhancement/current semester
danilolic/mwcrawler pull request #15
Opened 2018-10-12 18:37 UTC by rodriggochaves

Olá!

Nesse PR, eu criei o método `Mwcrawler::Crawler#semester` que retorna o semestre atual conforme a página do matrícula web.

Além disso, fiz algumas refatorações: 

1) movi a classe `Mwcrawler::Crawler` para um arquivo novo, `lib/mwcrawler/crawler.rb`, para respeitar a hierarquia de módulos do ruby e essa classe ter seu próprio arquivo;
2) movi a constante `SITE` para `lib/mwcrawler.rb` para esta ficar mais alta na hierarquia de módulos.

2018-10-13 16:57 UTC, vitorp requested changes
Só pedir pra dar uma olhada no rubocop (caso não tenha feito) e resolver o conflito com a master

2018-10-13 16:57 UTC, vitorp commented on spec/mwcrawler/crawler_spec.rb
> +      expect(subject.semester).to eq('2018/2')
Você pode verificar se Rubocop está reclamando desse subject? Ainda não configuramos a integração continua desse projeto.

2018-10-13 17:58 UTC, rodriggochaves commented
O que acha de adicionar o `rubocop` como `dev dependency`?

2018-10-21 16:04 UTC, danilodelyima commented on lib/mwcrawler/crawler.rb
> +      page = Helpers.set_crawler(nil, 'graduacao/default.aspx', {exact: true})
Olha o Rubocop aqui também

2018-10-21 16:05 UTC, danilodelyima commented
Se você puder adicionar o Rubocop como dev dependency eu agradeço também

2018-10-21 19:33 UTC, merged