Implementa crawler de subjects
danilolic/mwcrawler pull request #7
Opened 2018-10-01 22:09 UTC by danilodelyima

Pode receber dois parâmetros: campus ou id e um hash de options.
Se os campos ficarem em branco por default o crawler buscará todas as matérias do Campus Darcy Ribeiro

Caso o scrap seja por id, deverá também ser passado um flag dentro do hash de options `{ by_id: true }`

`Mwcrawler::Crawler.subjects(campus_or_id = :darcy_ribeiro, options = { log: false, by_id: false })` 
#5

2018-10-03 16:53 UTC, vitorp requested changes
Fiz algumas observações no código.

2018-10-03 16:53 UTC, vitorp commented on lib/mwcrawler/subjects.rb
> +      { code: page.css('#datatable')[0].css('tr:nth-child(2) td').text,
Acho que seria bom fazer uma conversão dos codigos para inteiros. concorda?

2018-10-03 16:53 UTC, vitorp commented on lib/mwcrawler/subjects.rb
> +      page = Nokogiri::HTML(URI.open(SITE + 'graduacao/oferta_dados.aspx?cod=' + id.to_s))
Eu to fazendo uma abordagem de ao invês de usar o URI open direto usar o set_crawler. Ai depois a gente só da uma refatorada no set_crawler. Essa ficaria tipo `Helpers.set_crawle(id, 'graduacao/oferta_dados.aspx?cod=')`

2018-10-03 16:53 UTC, vitorp commented on spec/mwcrawler_spec.rb
> +            @subjects = Mwcrawler::Crawler.new.subjects(campus)
Esse teste ta demorando muito? Se estiver pode ser um _code smell_ e seria melhor a gente tirar o teste e talvez até essa funcionalidade.

2018-10-03 16:53 UTC, vitorp commented on spec/mwcrawler_spec.rb
> +          @subject = Mwcrawler::Crawler.new.subjects('116441', {log:false, by_id: true})
Se não me engano rola de fazer um `Mwcrawler::Crawler.new.subjects('116441', by_id: true)` as chaves que você não passa no options hash ficam com o valor default mesmo.

2018-10-03 16:53 UTC, vitorp commented on spec/mwcrawler_spec.rb
> +        expect(@subject).to be_a_kind_of Hash
Seria bom adicionar uns testes pra verificar se os valores estão vindo corretos.

2018-10-03 16:53 UTC, vitorp commented on spec/mwcrawler_spec.rb
> +          expect(@subjects).to be_a_kind_of Array
Aqui eu acho que precisa de uns testes pra ver se não ta vazio e testar um pouco mais o conteudo.

2018-10-13 00:10 UTC, danilodelyima commented on spec/mwcrawler_spec.rb
> +            @subjects = Mwcrawler::Crawler.new.subjects(campus)
Demora em torno de 32 segundos para rodar o teste, de fato é muito tempo. Por que seria o caso de talvez tirar a funcionalidade? Como ficaria?

2018-10-13 00:13 UTC, danilodelyima commented on lib/mwcrawler/subjects.rb
> +      page = Nokogiri::HTML(URI.open(SITE + 'graduacao/oferta_dados.aspx?cod=' + id.to_s))
De fato é bom manter o padrão usando o helper

2018-10-13 00:15 UTC, danilodelyima commented on lib/mwcrawler/subjects.rb
> +      { code: page.css('#datatable')[0].css('tr:nth-child(2) td').text,
Inclusive os códigos de departamento também

2018-10-13 00:15 UTC, danilodelyima commented on spec/mwcrawler_spec.rb
> +          @subject = Mwcrawler::Crawler.new.subjects('116441', {log:false, by_id: true})
De fato.

2019-09-17 14:13 UTC, wladimirgramacho approved these changes

2019-09-17 14:19 UTC, merged